language: node_js
node_js: stable
install:
- npm install
script:
- sync
- hexo g
- hexo d
- rm -rf ~/.ssh
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_c2f92b25f22f_key -iv $encrypted_c2f92b25f22f_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Vincent"
- git config --global user.email "intelligentvincent@gmail.com"
