language: node_js
node_js: stable
install:
- npm install
script:
- hexo g
- hexo d
- rm -rf ~/.ssh

branches:
  only:
  - hexo

before_install:
- openssl aes-256-cbc -K $encrypted_0258d8bf4e05_key -iv $encrypted_0258d8bf4e05_iv
  -in id_rsa.enc -out /tmp/tra/id_rsa -d
  # Set the permission of the key
- chmod 600 ~/.ssh/id_rsa
# Start SSH agent
- eval $(ssh-agent)
# Add the private key to the system
- ssh-add ~/.ssh/id_rsa
# Copy SSH config
- cp .travis/ssh_config ~/.ssh/config
# Set Git config
- git config --global user.name "Vincent"
- git config --global user.email "intelligentvincent@gmail.com"
