# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 魏晨的博客
subtitle: 活在自己的年纪里
description: Vincent's Blog
keywords: 
  - Python
  - Linux
author: Vincent
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://weichen.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
theme_config:
  favicon:
    small: /favicon.ico
    medium: /favicon.ico
    apple_touch_icon: /favicon.ico
    safari_pinned_tab: /favicon.ico
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml
  # Console reminder if new version released.
  reminder: true

  # Remove unnecessary files after hexo generate.
  minify: true

  keywords: "魏晨, 博客"

  sidebar:
    position: left
    display: always

  footer:
    since: 2015
    icon:
      # Icon name in Font Awesome. See: https://fontawesome.com/v4.7.0/icons/
      # `heart` is recommended with animation in red (#ff0000).
      name: heart
      # If you want to animate the icon, set it to true.
      animated: true
      # Change the color of icon, using Hex Code.
      color: "#ff0000"


  menu:
    home: / || home
    标签: /tags/ || tags
    分类: /categories/ || th
    archives: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat
    关于: /about/ || user

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  scheme: Pisces

  social:
    GitHub: https://github.com/vc5 || github
    E-Mail: mailto:intelligentvincent#gmail.com || envelope
    Twitter: https://twitter.com/vincent_qaq || twitter
    Weibo: https://weibo.com/weichen92 || weibo

  avatar: /images/avatar.jpg
  # Creative Commons 4.0 International License.
  # See: https://creativecommons.org/share-your-work/licensing-types-examples
  # Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
  # You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
  # CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
  creative_commons:
    license: by-nc-sa
    sidebar: false
    post: true
    language: deed.zh

  baidu_analytics: 321fcbb44f19110036217f657d323e1e
  
  valine:
    enable: false
    appid:  Weres8VKraIetH90wimrTc4G-gzGzoHsz
    appkey:  PkxXld3YxxoIXfbARQTHBq8G
    notify: true
    verify: false # Verification code
    placeholder: 来啊，快活啊
    avatar: identicon
    guest_info: nick,mail # custom comment header
    pageSize: 10 # pagination size

  disqus:
    enable: true
    shortname: vc5
    count: true
  leancloud_visitors:
    enable: true
    app_id: Weres8VKraIetH90wimrTc4G-gzGzoHsz
    app_key: PkxXld3YxxoIXfbARQTHBq8G
  # Local Search
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    # Preload the search data when the page loads.
    preload: false

  # SEO 设置
  seo: true
  # See: https://www.google.com/webmasters
  google_site_verification: AQjF_MCWdRUkwlxn0xsw87CSwA0ppA8L6Vhl4ioli9k
  # Baidu Webmaster tools verification.
  # See: https://ziyuan.baidu.com/site
  baidu_site_verification: d8ajVhGFDE

  # Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO.
  baidu_push: true

  # CDN设置  
  vendors:
  # MathJax
    mathjax: //cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # DisqusJS
    disqusjs_js: //cdn.jsdelivr.net/npm/disqusjs@1/dist/disqus.js
    disqusjs_css: //cdn.jsdelivr.net/npm/disqusjs@1/dist/disqusjs.css
  # Internal version: 1.2.1
    velocity: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.min.js
    velocity_ui: //cdn.jsdelivr.net/npm/velocity-animate@1/velocity.ui.min.js
  
  # Internal version: 4.7.0
    fontawesome: //cdn.jsdelivr.net/npm/font-awesome@4/css/font-awesome.min.css


sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml



# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: 
      github: git@vc5.github.com:vc5/vc5.github.io.git,master