# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 魏晨的博客
subtitle: 活在自己的年纪里
description: Vincent's Blog
keywords: 
  - Python
  - Linux
author: Vincent
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://weichen.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
theme_config:
  favicon:
    small: /favicon.ico
    medium: /favicon.ico
    apple_touch_icon: /favicon.ico
    safari_pinned_tab: /favicon.ico
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml

  keywords: "魏晨, 博客"

  sidebar:
    position: left
    display: always

  # motion:
  #   enable: true

  footer:
    since: 2015
    icon: heart

  seo: true

  menu:
    主页: / || home
    标签: /tags/ || tags
    分类: /categories/ || th
    存档: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat
    关于: /about/ || user

  scheme: Pisces

  social:
    GitHub: https://github.com/vc5 || github
    E-Mail: mailto:intelligentvincent#gmail.com || envelope
    Twitter: https://twitter.com/vincent_qaq || twitter
    Weibo: https://weibo.com/weichen92 || weibo

  avatar: /images/avatar.jpg
  creative_commons: by-nc-sa
  baidu_analytics: 321fcbb44f19110036217f657d323e1e
  disqus:
    enable: true
    shortname: vc5
    count: true
  # youyan_uid: 2130659
  jiathis: true
  add_this_id: 2130959
  leancloud_visitors:
    enable: true
    app_id: Weres8VKraIetH90wimrTc4G-gzGzoHsz
    app_key: PkxXld3YxxoIXfbARQTHBq8G
  local_search:
    enable: true



sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

## 七牛同步
qiniu:
  offline: false
  sync: true
  bucket: weichen
  secret_file: secret/qn.json
  dirPrefix: vc5
  urlPrefix: http://7xn70q.com1.z0.glb.clouddn.com/vc5
  up_host: http://upload.qiniu.com
  local_dir: static
  update_exist: true
  image: 
    folder: images
    extend: 
  js:
    folder: js
  css:
    folder: css

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: 
      github: git@vc5.github.com:vc5/vc5.github.io.git,master
      coding: git@git.coding.net:vc5/vc5.coding.me.git,master